---


name: "Simple Github Actions Workflow"


on:

  push:
    branches:
      - master
      - testing
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: "running date command"
        run: date
        shell: bash

      - name: "Getting os details"
        run: cat /etc/os-release
        shell: bash
     
      - name: "user Details"
        run: whoami
        shell: bash

      - name: "Current Working Directory Details Before Checkout"
        run: |
          pwd
          ls -al 

      - name: "checkout Repository"
        uses: actions/checkout@v3

      - name: "Current Working Directory Details After Checkout"
        run: |
         pwd
         ls -al

      - name: "Installing Terraform"
        run: |
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          ./terraform version
          ls -al 

      - name: "Running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh

